### ISSUE TITLE
项目下其他组件的编译好的程序

### ISSUE THREAD

**Issue by Sokwva** [wpscott/AcFunDanmaku#1]
弱弱地问一下这个项目下其他组件有编译好的程序吗

**Comment by wpscott** [comment]
未编译通常是还在开发中的，会有很多bug或者随机闪退等情况发生。
如果你不介意的话，我抽空编译一遍。

**Comment by Sokwva** [comment]
好的，谢谢了

**Comment by wpscott** [comment]
编译已发布

**Comment by TerryYoung518** [comment]
请问目前编译好的程序还会更新吗？例如，希望能在AcFunDMJ的ws通讯数据中包含用户的uid，这样用户头像也能在前端通过`https://live.acfun.cn/rest/pc-direct/user/userInfo?userId=`获取到，目前只有用户昵称，获取不到用户头像，也比较难应对某些用户改名的情况。

**Comment by wpscott** [comment]
> 请问目前编译好的程序还会更新吗？例如，希望能在AcFunDMJ的ws通讯数据中包含用户的uid，这样用户头像也能在前端通过`https://live.acfun.cn/rest/pc-direct/user/userInfo?userId=`获取到，目前只有用户昵称，获取不到用户头像，也比较难应对某些用户改名的情况。

抱歉，目前精力有限，只有[核心功能模块](https://github.com/wpscott/AcFunDanmaku/tree/master/AcFunDanmu)，会保持在[NuGet](https://www.nuget.org/packages/AcFunDanmu/)上更新。

### 对于AcFunDMJ
ws通讯数据，例如[评论](https://github.com/wpscott/AcFunDanmaku/blob/master/AcFunDanmu/protos/zt.live.interactive/CommonActionSignalComment.proto)、[礼物](https://github.com/wpscott/AcFunDanmaku/blob/master/AcFunDanmu/protos/zt.live.interactive/CommonActionSignalGift.proto)、[点赞](https://github.com/wpscott/AcFunDanmaku/blob/master/AcFunDanmu/protos/zt.live.interactive/CommonActionSignalLike.proto)、[进入](https://github.com/wpscott/AcFunDanmaku/blob/master/AcFunDanmu/protos/zt.live.interactive/CommonActionSignalUserEnterRoom.proto)、[关注](https://github.com/wpscott/AcFunDanmaku/blob/master/AcFunDanmu/protos/zt.live.interactive/CommonActionSignalUserFollowAuthor.proto)等中，包含的用户信息可以参考[ZtLiveUserInfo.proto](https://github.com/wpscott/AcFunDanmaku/blob/master/AcFunDanmu/protos/zt.live.interactive/ZtLiveUserInfo.proto)。
通过修改[#L116](https://github.com/wpscott/AcFunDanmaku/blob/master/AcFunDMJ/Pages/ChatBox.razor#L116)增加`long Id { get; set; }`以及[#L201](https://github.com/wpscott/AcFunDanmaku/blob/master/AcFunDMJ/Pages/ChatBox.razor#L201)`UpdateDanmaku(new Comment { Id = comment.UserInfo.UserId; Name = comment.UserInfo.Nickname, Content = comment.Content; });`即可增加用户UID信息。
