### ISSUE TITLE
qq 频道搜不到了

### ISSUE THREAD

**Issue by zhangguanzhang** [wpscott/AcFunDanmaku#17]
搜了下没有了

**Comment by wpscott** [comment]
可以试试搜索频道号`170db2421u`

**Comment by zhangguanzhang** [comment]
> 可以试试搜索频道号`170db2421u`

看了半天搜索里没有地方输入频道号码搜索之类的

**Comment by wpscott** [comment]
> > 可以试试搜索频道号`170db2421u`
> 
> 看了半天搜索里没有地方输入频道号码搜索之类的

![170db2421u](https://user-images.githubusercontent.com/6392170/166610372-ebf3cd3c-ecae-4db5-8d09-8ad72628e81e.png)

**Comment by zhangguanzhang** [comment]
![QQ图片20220504124414](https://user-images.githubusercontent.com/18641678/166624161-03ebb59c-bd47-447c-962d-842c50f3930d.jpg)
![QQ图片20220504124419](https://user-images.githubusercontent.com/18641678/166624208-0d5b9beb-ea92-414e-a358-c06d801f19d1.jpg)

搜不到哦

**Comment by wpscott** [comment]
![cid](https://user-images.githubusercontent.com/6392170/166643700-b078de42-9125-4f5a-9c92-1a328661bfc1.png)
