### ISSUE TITLE
连接时候发生一个异常

### ISSUE THREAD

**Issue by lcfzblcfzb** [wpscott/AcFunDanmaku#18]
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values.
  Source=System.Private.CoreLib
  StackTrace:
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
   在 System.ReadOnlySpan`1.Slice(Int32 start, Int32 length)
   在 AcFunDanmu.ClientUtils.Decode[T](ReadOnlySpan`1& bytes, String& SecurityKey, String& SessionKey, PacketHeader& header) 在 D:\C#PROJ\ACDANMU_DEMO\WebApplication1\AcFunDanmu\ClientUtils.cs 中: 第 172 行
   在 AcFunDanmu.Client.<Start>d__61.MoveNext() 在 D:\C#PROJ\ACDANMU_DEMO\WebApplication1\AcFunDanmu\Client.cs 中: 第 743 行

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    AcFunDanmu.ClientUtils.Decode<T>(System.ReadOnlySpan<byte>, string, string, out AcFunDanmu.Im.Basic.PacketHeader) (位于 ClientUtils.cs 中)
    AcFunDanmu.Client.Start() (位于 Client.cs 中)

**Comment by wpscott** [comment]
已修复：https://github.com/wpscott/AcFunDanmaku/commit/97d5386919876f87a7458f04b6a70f6e8503b12b

**Comment by lcfzblcfzb** [comment]
好滴 大佬 AC频道真搜索不到

**Comment by wpscott** [comment]
试试这个[点击链接加入QQ频道【AcFun开源⑨课】](https://qun.qq.com/qqweb/qunpro/share?inviteCode=pAph5&businessType=9&biz=ka)

**Comment by lcfzblcfzb** [comment]
> 

uuid633228 大佬通过一下

**Comment by orzogc** [comment]
没看到有申请通知
