### ISSUE TITLE
关于编译

### ISSUE THREAD

**Issue by RtekiX** [wpscott/AcFunDanmaku#3]
编译用到.NET CORE 3.1，但是Visual Studio 2017似乎没有办法使用3.1的框架
想问一下有没有其他使用方法

**Comment by wpscott** [comment]
根据文档，编译.Net Core 3需要MSBuild16.3.0以上的版本。所以
1. 使用VS2019
2. 下载最新的[MSBuild](https://github.com/microsoft/msbuild/releases)，然后根据[dotnet cli](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-msbuild)和[msbuild cli](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019)来编译。

**Comment by RtekiX** [comment]
了解，谢谢
