### ISSUE TITLE
A站直播源API的问题

### ISSUE THREAD

**Issue by orzogc** [wpscott/AcFunDanmaku#6]
POST `https://api.kuaishouzt.com/rest/zt/live/web/startPlay...` 只会返回 `{"result":52,"error_msg":"","host":"public-sc-kcs-node73.idcyz.hb1.kwaidc.com"}` ，但我看网页版直播是会返回直播源相关信息
以前是正常的，今天中午突然变这样

**Comment by wpscott** [comment]
看@luyuofficial 说是加了refer头验证

**Comment by orzogc** [comment]
的确是验证refer头
